include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error Rules
    - annotate_overrides
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - discarded_futures
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_logic_in_create_state
    - no_runtimeType_toString
    - prefer_void_to_null
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - valid_regexps

    # Style Rules
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - conditional_uri_does_not_exist
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - deprecated_consistency
    - do_not_use_environment
    - eol_at_end_of_file
    - flutter_style_todos
    - leading_newlines_in_multiline_strings
    - matching_super_parameters
    - no_leading_underscores_for_local_identifiers
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_this
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - void_checks

    # Pub Rules
    - depend_on_referenced_packages
    - package_names
    - sort_pub_dependencies
